### ISSUE TITLE
Run start_servers.bat from Visual Studio Code.

### ISSUE THREAD

**Issue by danielsoy** [intelec-ai/intelecai-installation#1]
Hello Huseyn.

Congratulations for your development, I hope you are doing well.

I was trying to run start_server.bat from visual studio code, via docker, without success.

Please look:
https://www.youtube.com/watch?v=HTCVs38wDpE&ab_channel=tektronix475
https://www.youtube.com/watch?v=qcmOfih7zSg&ab_channel=tektronix475

Am I doing something wrong?

Thank you so much!

**Comment by hgasimov** [comment]
Hi Daniel. It might be some visual studio incompatibility. Options to test:

- Double click on the start_servers.bat file in the windows folder
- Open a windows terminal and copy-paste the lines in start_servers.bat one by one and execute
- Run in the terminal, "docker info" to test whether docker is working properly

**Comment by danielsoy** [comment]
Thanks Huseyn, I got access after pulling the image, from intelecai/automl_server

Choosing this option: Double click on the **start_servers.bat** file in the windows folder.
 
Now I want to experiment with some model, appropiate for anomaly detection.

I have watched your youtube video:

https://www.youtube.com/watch?v=Ra3hYQMs1dc&ab_channel=IntelecAI

 And I would like try something similar.

**Comment by intelec-ai** [comment]
Ok, good luck :)

**Comment by danielsoy** [comment]
Almost there...

When I click on the START button to start trainning, asks for confirmation, I click on YES
 and STATUS changes to: **running**, the percentage stays in 0%, and a couple of seconds
after, STATUS gets back to : **not running**.

**Comment by hgasimov** [comment]
You need to check the docker logs of intelec-backend service

1. Get the ID of the docker service intelec-backend by running "docker
service ls"

2. Run "docker service logs [serviceID]"

One possible cause of your problem is that your dataset is not in correct
format.

**Comment by danielsoy** [comment]
yes, maybe the dataset is to blame.

I will search for another short dataset, known for working well.

**Comment by danielsoy** [comment]
Do I need a CUDA GPU, for trainning by the way?

**Comment by intelec-ai** [comment]
No, you dont have to have CUDA for training.

**Comment by danielsoy** [comment]
I cant find anything wrong with my log... I guess.

[docker service log.txt](https://github.com/intelec-ai/intelecai-installation/files/7611683/docker.service.log.txt)

**Comment by hgasimov** [comment]
You need to click on the "Start" button on the training page to let the training start and stop. Then you can get the docker log of intelec_backend service.

**Comment by danielsoy** [comment]
I got : Could not do one pass in your dataloader, there is something wrong in it
at some point inside the log file

[log.txt](https://github.com/intelec-ai/intelecai-installation/files/7621281/log.txt)

I have chosen to put my two classes data, inside two separated folders, without a .cvs file, for labels(option 1).
Is that correct? or a csv with labes is always needed, despite having two folders, one for each class?
.****

**Comment by hgasimov** [comment]
You can watch [this video](https://youtu.be/7qJ6chU_5UE) to learn about how you can train an image classifier. There are also videos about [object detection](https://youtu.be/wuVh1X-HbJ8) and [image segmentation](https://youtu.be/T9EfYzjpevQ). 

Please also check that your image folders contain only images, no text files, no hidden files (.DS_Store, .Trash, .git, etc).
